const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@Hussain Devs";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "*******";
const retypePass = "ReType Password";
const name = "Name";
const nameHint = "Hussain";
const forgetPass = "Forget Password";
const login = "Log In";
const signup = "Sign Up";
const createNewAcc = "or , Create a new account";
const loginwith = "Log in with";
const privPolicy = "Privacy Policy";
const termandCon = "Terms and Conditions";
const alreadyhaveandAcc = "Already have an account? ";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";

//home_Screen string
const searchforanything = "Search anything",
    todayDeal = "Today's Deal",
    flashDeal = "Flash Deal",
    topSeller = "Top Sellers",
    brand = "Brands",
    topCategories = "Top Categories",
    womenDress = "Women Dresses",
    girlswatches = "Girls Watches",
    mobilephone = "Mobile Phones",
    boysglasses = "Boys Glasses",
    tshirts = "Tshirts",
    girlsDresses = "Girls Dresses",
    featuredProduct = "Featured Products",
    featuredCategories = "Featured Categories";

const womenClothing = "Women Clothing",
    menClothing = "Men Clothing",
    kidstoys = "Kids Toys",
    sports = "Sports",
    jewelery = "Jewelery",
    cellphones = "Cellphones",
    furniture = "Furniture",
    automobiles = "Automobiles",
    compAccess = "Computer & Accessories";
